#! /bin/sh

bspc monitor DP-2 --remove
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

display_check &
polybar left &
polybar center &
polybar right &
sxhkd &
gentoo-pipewire-launcher &
picom &
xrdb ~/.Xresources &
